# Generated by Django 4.2.3 on 2023-07-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_uans_id_question_uquest_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='ans',
        ),
        migrations.AlterField(
            model_name='answer',
            name='uans_id',
            field=models.CharField(default='a1f57e9a6c8b', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uquest_id',
            field=models.CharField(default='ff242c8029da', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
    ]
