# Generated by Django 4.2.3 on 2023-07-25 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_rename_answer_answer_ans_alter_answer_uans_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterField(
            model_name='answer',
            name='uans_id',
            field=models.CharField(default='9536276734db', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uquest_id',
            field=models.CharField(default='b7fef90dba17', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('answer', 'user')},
            },
        ),
    ]
