# Generated by Django 4.2.3 on 2023-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='uans_id',
            field=models.CharField(default='b64c87541e6f', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uquest_id',
            field=models.CharField(default='09fe8ff21da3', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
    ]
