# Generated by Django 4.2.3 on 2023-07-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_answer_uans_id_alter_question_uquest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='uans_id',
            field=models.CharField(default='36cb3dcbf9ef', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uquest_id',
            field=models.CharField(default='b8ceae77a805', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
    ]
